export const internationalCode = [
  {
    id: 0,
    label: '대한민국',
    value: '82',
    code: '+82',
    enLabel: 'South Korea',
  },
  {
    id: 1,
    label: '가나',
    value: '233',
    code: '+233',
    enLabel: 'Ghana',
  },
  { id: 2, label: '가봉', value: '241', code: '+241', enLabel: 'Gabon' },
  {
    id: 3,
    label: '가이아나',
    value: '592',
    code: '+592',
    enLabel: 'Guyana',
  },
  {
    id: 4,
    label: '감비아',
    value: '220',
    code: '+220',
    enLabel: 'Gambia',
  },
  {
    id: 5,
    label: '괌',
    value: '1671',
    code: '+1671',
    enLabel: 'Guam',
  },
  {
    id: 6,
    label: '과들루프',
    value: '590',
    code: '+590',
    enLabel: 'Guadeloupe',
  },
  {
    id: 7,
    label: '과테말라',
    value: '502',
    code: '+502',
    enLabel: 'Guatemala',
  },
  {
    id: 8,
    label: '그레나다',
    value: '1473',
    code: '+1473',
    enLabel: 'Grenada',
  },
  {
    id: 9,
    label: '그리스',
    value: '30',
    code: '+30',
    enLabel: 'Greece',
  },
  {
    id: 10,
    label: '그린란드',
    value: '299',
    code: '+299',
    enLabel: 'Greenland',
  },
  {
    id: 11,
    label: '기니',
    value: '224',
    code: '+224',
    enLabel: 'Guinea',
  },
  {
    id: 12,
    label: '기니비사우',
    value: '245',
    code: '+245',
    enLabel: 'Guinea-Bissau',
  },
  {
    id: 13,
    label: '나미비아',
    value: '264',
    code: '+264',
    enLabel: 'Namibia',
  },
  {
    id: 14,
    label: '나우루',
    value: '674',
    code: '+674',
    enLabel: 'Nauru',
  },
  {
    id: 15,
    label: '나이지리아',
    value: '234',
    code: '+234',
    enLabel: 'Nigeria',
  },
  {
    id: 16,
    label: '남수단',
    value: '211',
    code: '+211',
    enLabel: 'South Sudan	',
  },
  {
    id: 17,
    label: '남아프리카공화국',
    value: '27',
    code: '+27',
    enLabel: 'South Africa',
  },
  {
    id: 18,
    label: '네덜란드',
    value: '31',
    code: '+31',
    enLabel: 'the Netherlands',
  },
  { id: 19, label: '네팔', value: '977', code: '+977', enLabel: 'Nepal' },
  { id: 20, label: '노르웨이', value: '47', code: '+47', enLabel: 'Norway' },
  {
    id: 21,
    label: '누벨칼레도니',
    value: '687',
    code: '+687',
    enLabel: 'New Caledonia',
  },
  {
    id: 22,
    label: '뉴질랜드',
    value: '64',
    code: '+64',
    enLabel: 'New Zealand',
  },
  { id: 23, label: '니우에', value: '683', code: '+683', enLabel: 'Niue' },
  { id: 24, label: '니제르', value: '227', code: '+227', enLabel: 'Niger' },
  {
    id: 25,
    label: '니카라과',
    value: '505',
    code: '+505',
    enLabel: 'Nicaragua',
  },
  { id: 26, label: '덴마크', value: '45', code: '+45', enLabel: 'Denmark' },
  {
    id: 27,
    label: '도미니카 공화국',
    value: '1809',
    code: '+1809',
    enLabel: 'Dominican R.',
  },
  {
    id: 28,
    label: '도미니카 연방',
    value: '1767',
    code: '+1767',
    enLabel: 'Dominica',
  },
  { id: 29, label: '독일', value: '49', code: '+49', enLabel: 'Germany' },
  {
    id: 30,
    label: '동티모르',
    value: '670',
    code: '+670',
    enLabel: 'East Timor',
  },
  { id: 31, label: '라오스 +856', value: '856', code: '+856', enLabel: 'Laos' },
  {
    id: 32,
    label: '라이베리아',
    value: '231',
    code: '+231',
    enLabel: 'Liberia',
  },
  { id: 33, label: '라트비아', value: '371', code: '+371', enLabel: 'Latvia' },
  { id: 34, label: '러시아', value: '7', code: '+7', enLabel: 'Russia' },
  { id: 35, label: '레바논', value: '961', code: '+961', enLabel: 'Lebanon' },
  { id: 36, label: '레소토', value: '266', code: '+266', enLabel: 'Lesotho' },
  { id: 37, label: '루마니아', value: '40', code: '+40', enLabel: 'Romania' },
  {
    id: 38,
    label: '룩셈부르크',
    value: '352',
    code: '+352',
    enLabel: 'Luxembourg',
  },
  { id: 39, label: '르완다', value: '250', code: '+250', enLabel: 'Rwanda' },
  { id: 40, label: '리비아', value: '218', code: '+218', enLabel: 'Libya' },
  {
    id: 41,
    label: '리투아니아',
    value: '370',
    code: '+370',
    enLabel: 'Lithuania',
  },
  {
    id: 42,
    label: '리히텐슈타인',
    value: '423',
    code: '+423',
    enLabel: 'Liechtenstein',
  },
  {
    id: 43,
    label: '마다가스카르',
    value: '261',
    code: '+261',
    enLabel: 'Madagascar',
  },
  {
    id: 44,
    label: '마르티니크',
    value: '596',
    code: '+596',
    enLabel: 'Martinique',
  },
  {
    id: 45,
    label: '마셜 제도',
    value: '692',
    code: '+692',
    enLabel: 'Marshall Islands',
  },
  { id: 46, label: '마요트', value: '269', code: '+269', enLabel: 'Mayotte' },
  { id: 47, label: '마카오', value: '853', code: '+853', enLabel: 'Macao' },
  { id: 48, label: '말라위', value: '265', code: '+265', enLabel: 'Malawi' },
  {
    id: 49,
    label: '말레이시아',
    value: '60',
    code: '+60',
    enLabel: 'Malaysia',
  },

  { id: 50, label: '말리', value: '223', code: '+223', enLabel: 'Mali' },
  { id: 51, label: '멕시코', value: '52', code: '+52', enLabel: 'Mexico' },
  {
    id: 52,
    label: '모나코',
    value: '377',
    code: '+377',
    enLabel: 'Monaco',
  },
  {
    id: 53,
    label: '모로코',
    value: '212',
    code: '+212',
    enLabel: 'Morocco',
  },
  {
    id: 54,
    label: '모리셔스',
    value: '230',
    code: '+230',
    enLabel: 'Mauritius',
  },
  {
    id: 55,
    label: '모리타니',
    value: '222',
    code: '+222',
    enLabel: 'Mauritania',
  },
  {
    id: 56,
    label: '모잠비크',
    value: '258',
    code: '+258',
    enLabel: 'Mozambique',
  },

  {
    id: 57,
    label: '몬테네그로',
    value: '382',
    code: '+382',
    enLabel: 'Montenegro',
  },
  {
    id: 58,
    label: '몬트세랫',
    value: '1664',
    code: '+1664',
    enLabel: 'Montserrat',
  },

  {
    id: 59,
    label: '몰도바',
    value: '373',
    code: '+373',
    enLabel: 'Maldova',
  },
  {
    id: 60,
    label: '몰디브',
    value: '960',
    code: '+960',
    enLabel: 'Maldives',
  },
  { id: 61, label: '몰타', value: '356', code: '+356', enLabel: 'Malta' },
  { id: 62, label: '몽골', value: '976', code: '+976', enLabel: 'Mongolia' },
  { id: 63, label: '미국', value: '1', code: '+1', enLabel: 'United States' },
  { id: 64, label: '미얀마', value: '95', code: '+95', enLabel: 'Myanmar' },

  {
    id: 65,
    label: '미크로네시아 연방',
    value: '691',
    code: '+691',
    enLabel: 'Micronesia',
  },
  { id: 66, label: '바누아투', value: '678', code: '+678', enLabel: 'Vanuatu' },
  { id: 67, label: '바레인', value: '973', code: '+973', enLabel: 'Bahrain' },
  {
    id: 68,
    label: '바베이도스',
    value: '1246',
    code: '+1246',
    enLabel: 'Barbados',
  },

  {
    id: 69,
    label: '바티칸 시국',
    value: '379',
    code: '+379',
    enLabel: 'Vatican',
  },
  { id: 70, label: '바하마', value: '1242', code: '+1242', enLabel: 'Bahamas' },
  {
    id: 71,
    label: '방글라데시',
    value: '880',
    code: '+880',
    enLabel: 'Bangladesh',
  },
  { id: 72, label: '버뮤다', value: '1441', code: '+1441', enLabel: 'Bermuda' },
  { id: 73, label: '베냉', value: '229', code: '+229', enLabel: 'Benin' },
  {
    id: 74,
    label: '베네수엘라',
    value: '58',
    code: '+58',
    enLabel: 'Venezuela',
  },
  { id: 75, label: '베트남', value: '84', code: '+84', enLabel: 'Vietnam' },
  { id: 76, label: '벨기에', value: '32', code: '+32', enLabel: 'Belgium' },
  { id: 77, label: '벨라루스', value: '375', code: '+375', enLabel: 'Belarus' },
  { id: 78, label: '벨리즈', value: '501', code: '+501', enLabel: 'Belize' },
  {
    id: 79,
    label: '보스니아 헤르체고비나',
    value: '387',
    code: '+387',
    enLabel: 'Bosnia and Herzegovina',
  },
  {
    id: 80,
    label: '보츠와나',
    value: '267',
    code: '+267',
    enLabel: 'Botswana',
  },
  { id: 81, label: '볼리비아', value: '591', code: '+591', enLabel: 'Bolivia' },
  { id: 82, label: '부룬디', value: '257', code: '+257', enLabel: 'Burundi' },
  {
    id: 83,
    label: '부르키나파소',
    value: '226',
    code: '+226',
    enLabel: 'Burkina Faso',
  },
  { id: 84, label: '부탄', value: '975', code: '+975', enLabel: 'Bhutan' },
  {
    id: 85,
    label: '북마케도니아',
    value: '389',
    code: '+389',
    enLabel: 'Macedonia',
  },
  {
    id: 86,
    label: '불가리아',
    value: '359',
    code: '+359',
    enLabel: 'Bulgaria',
  },
  { id: 87, label: '브라질', value: '55', code: '+55', enLabel: 'Brazil' },
  { id: 88, label: '브루나이', value: '673', code: '+673', enLabel: 'Brunei' },
  { id: 89, label: '사모아', value: '685', code: '+685', enLabel: 'Samoa' },
  {
    id: 90,
    label: '사우디아라비아',
    value: '966',
    code: '+966',
    enLabel: 'Saudi Arabia',
  },
  {
    id: 91,
    label: '산마리노',
    value: '378',
    code: '+378',
    enLabel: 'San Marino',
  },
  {
    id: 92,
    label: '생피에르 미클롱',
    value: '508',
    code: '+508',
    enLabel: 'Saint Pierre and Miquelon',
  },
  {
    id: 93,
    label: '서사하라',
    value: '212',
    code: '+212',
    enLabel: 'Western Sahara',
  },
  { id: 94, label: '세네갈', value: '221', code: '+221', enLabel: 'Senegal' },
  { id: 95, label: '세르비아', value: '381', code: '+381', enLabel: 'Serbia' },
  {
    id: 96,
    label: '세이셸',
    value: '248',
    code: '+248',
    enLabel: 'Seychelles',
  },
  {
    id: 97,
    label: '세인트루시아',
    value: '1758',
    code: '+1758',
    enLabel: 'Saint Lucia',
  },
  {
    id: 98,
    label: '세인트헬레나',
    value: '290',
    code: '+290',
    enLabel: 'Saint Helena',
  },
  { id: 99, label: '소말리아', value: '252', code: '+252', enLabel: 'Somalia' },
  {
    id: 100,
    label: '솔로몬 제도',
    value: '677',
    code: '+677',
    enLabel: 'Solomon Islands',
  },
  { id: 101, label: '수단', value: '249', code: '+249', enLabel: 'Sudan' },
  { id: 102, label: '수리남', value: '597', code: '+597', enLabel: 'Suriname' },
  { id: 103, label: '스리랑카', value: '94', code: '+94', enLabel: 'SriLanka' },
  { id: 104, label: '스웨덴', value: '46', code: '+46', enLabel: 'Sweden' },
  {
    id: 105,
    label: '스위스',
    value: '41',
    code: '+41',
    enLabel: 'Switzerland',
  },
  { id: 106, label: '스페인', value: '34', code: '+34', enLabel: 'Spain' },
  {
    id: 107,
    label: '슬로바키아',
    value: '421',
    code: '+421',
    enLabel: 'Slovakia',
  },
  {
    id: 108,
    label: '슬로베니아',
    value: '386',
    code: '+386',
    enLabel: 'Slovenia',
  },
  { id: 109, label: '시리아', value: '963', code: '+963', enLabel: 'Syria' },
  {
    id: 110,
    label: '시에라리온',
    value: '232',
    code: '+232',
    enLabel: 'Sierra Leone',
  },
  {
    id: 111,
    label: '신트마르턴 ',
    value: '1721',
    code: '+1721',
    enLabel: 'Sint Maarten',
  },
  {
    id: 112,
    label: '싱가포르',
    value: '65',
    code: '+65',
    enLabel: 'Singapore',
  },
  {
    id: 113,
    label: '아랍에미리트',
    value: '971',
    code: '+971',
    enLabel: 'United Arab Emirates',
  },
  { id: 114, label: '아루바', value: '297', code: '+297', enLabel: 'Aruba' },
  {
    id: 115,
    label: '아르메니아',
    value: '374',
    code: '+374',
    enLabel: 'Armenia',
  },
  {
    id: 116,
    label: '아르헨티나',
    value: '54',
    code: '+54',
    enLabel: 'Argentina',
  },
  {
    id: 117,
    label: '아메리칸사모아',
    value: '1684',
    code: '+1684',
    enLabel: 'American Samoa',
  },
  {
    id: 118,
    label: '아이슬란드',
    value: '354',
    code: '+354',
    enLabel: 'Iceland',
  },
  { id: 119, label: '아이티', value: '509', code: '+233', enLabel: 'Haiti' },
  {
    id: 120,
    label: '아일랜드',
    value: '353',
    code: '+353',
    enLabel: 'Ireland',
  },
  {
    id: 121,
    label: '아제르바이잔',
    value: '994',
    code: '+994',
    enLabel: 'Azerbaijan',
  },
  {
    id: 122,
    label: '아프가니스탄',
    value: '93',
    code: '+93',
    enLabel: 'Afghanistan',
  },
  { id: 123, label: '안도라', value: '376', code: '+376', enLabel: 'Andorra' },
  {
    id: 124,
    label: '알바니아',
    value: '355',
    code: '+355',
    enLabel: 'Albania',
  },
  { id: 125, label: '알제리', value: '213', code: '+213', enLabel: 'Algeria' },
  { id: 126, label: '앙골라', value: '244', code: '+244', enLabel: 'Angola' },
  {
    id: 127,
    label: '앤티가',
    value: '1268',
    code: '+1268',
    enLabel: 'Antigua and Barbuda',
  },
  {
    id: 128,
    label: '앵귈라',
    value: '1264',
    code: '+1264',
    enLabel: 'Anguilla',
  },
  {
    id: 129,
    label: '에리트레아',
    value: '291',
    code: '+291',
    enLabel: 'Eritrea',
  },
  {
    id: 130,
    label: '에스와티니',
    value: '268',
    code: '+268',
    enLabel: 'Eswatini',
  },
  {
    id: 131,
    label: '에스토니아',
    value: '372',
    code: '+372',
    enLabel: 'Estonia',
  },
  {
    id: 132,
    label: '에콰도르',
    value: '593',
    code: '+593',
    enLabel: 'Ecuador',
  },
  {
    id: 133,
    label: '에티오피아',
    value: '251',
    code: '+251',
    enLabel: 'Ethiopia',
  },
  {
    id: 134,
    label: '엘살바도르',
    value: '503',
    code: '+503',
    enLabel: 'El Salvador',
  },
  {
    id: 135,
    label: '영국',
    value: '44',
    code: '+44',
    enLabel: 'United Kingdom',
  },
  { id: 136, label: '예멘', value: '967', code: '+967', enLabel: 'Yemen' },
  { id: 137, label: '오만', value: '968', code: '+968', enLabel: 'Oman' },
  {
    id: 138,
    label: '오스트레일리아',
    value: '61',
    code: '+61',
    enLabel: 'Australia',
  },
  {
    id: 139,
    label: '오스트리아',
    value: '43',
    code: '+43',
    enLabel: 'Austria',
  },
  {
    id: 140,
    label: '온두라스',
    value: '504',
    code: '+504',
    enLabel: 'Honduras',
  },
  { id: 141, label: '요르단', value: '962', code: '+962', enLabel: 'Jordan' },
  { id: 142, label: '우간다', value: '256', code: '+256', enLabel: 'Uganda' },
  {
    id: 143,
    label: '우루과이',
    value: '598',
    code: '+598',
    enLabel: 'Uruguay',
  },
  {
    id: 144,
    label: '우즈베키스탄',
    value: '998',
    code: '+998',
    enLabel: 'Uzbekistan',
  },
  {
    id: 145,
    label: '우크라이나',
    value: '380',
    code: '+380',
    enLabel: 'Ukraine',
  },
  {
    id: 146,
    label: '이라크 +964',
    value: '964',
    code: '+964',
    enLabel: 'Iraq',
  },
  { id: 147, label: '이란', value: '98', code: '+98', enLabel: 'Iran' },
  { id: 148, label: '이스라엘', value: '972', code: '+972', enLabel: 'Israel' },
  { id: 149, label: '이집트', value: '20', code: '+20', enLabel: 'Egypt' },
  { id: 150, label: '이탈리아', value: '39', code: '+39', enLabel: 'Italy' },
  { id: 151, label: '인도', value: '91', code: '+91', enLabel: 'India' },
  {
    id: 152,
    label: '인도네시아',
    value: '62',
    code: '+62',
    enLabel: 'Indonesia',
  },
  { id: 153, label: '일본', value: '81', code: '+81', enLabel: 'Japan' },
  {
    id: 154,
    label: '자메이카',
    value: '1876',
    code: '+1876',
    enLabel: 'Jamaica',
  },
  { id: 155, label: '잠비아', value: '260', code: '+260', enLabel: 'Zambia' },
  {
    id: 156,
    label: '적도 기니',
    value: '240',
    code: '+240',
    enLabel: 'Equatorial Guinea',
  },
  {
    id: 157,
    label: '북한',
    value: '850',
    code: '+850',
    enLabel: 'DPR of Korea',
  },
  { id: 158, label: '조지아', value: '995', code: '+995', enLabel: 'Georgia' },
  {
    id: 159,
    label: '중앙아프리카 공화국',
    value: '236',
    code: '+236',
    enLabel: 'Central Africa',
  },
  { id: 160, label: '대만', value: '886', code: '+886', enLabel: 'Taiwan' },
  { id: 161, label: '중국', value: '86', code: '+86', enLabel: 'China' },
  { id: 162, label: '지부티', value: '253', code: '+253', enLabel: 'Djibouti' },
  {
    id: 163,
    label: '지브롤터',
    value: '350',
    code: '+350',
    enLabel: 'Gibraltar',
  },
  {
    id: 164,
    label: '짐바브웨',
    value: '263',
    code: '+263',
    enLabel: 'Zimbabwe',
  },
  { id: 165, label: '차드', value: '235', code: '+235', enLabel: 'Chad' },
  { id: 166, label: '체코', value: '420', code: '+420', enLabel: 'Czech' },
  { id: 167, label: '칠레', value: '56', code: '+56', enLabel: 'Chile' },
  { id: 168, label: '카메룬', value: '237', code: '+237', enLabel: 'Cameroon' },
  {
    id: 169,
    label: '카보베르데',
    value: '238',
    code: '+238',
    enLabel: 'Cape Verde',
  },
  {
    id: 170,
    label: '카자흐스탄',
    value: '7',
    code: '+7',
    enLabel: 'Kazakstan',
  },
  { id: 171, label: '카타르', value: '974', code: '+974', enLabel: 'Qatar' },
  {
    id: 172,
    label: '캄보디아',
    value: '855',
    code: '+855',
    enLabel: 'Cambodia',
  },
  { id: 173, label: '캐나다', value: '1', code: '+1', enLabel: 'Canada' },
  { id: 174, label: '케냐', value: '254', code: '+254', enLabel: 'Kenya' },
  {
    id: 175,
    label: '케이맨 제도',
    value: '1345',
    code: '+1345',
    enLabel: 'Cayman Islands',
  },
  {
    id: 176,
    label: '코모로',
    value: '269',
    code: '+269',
    enLabel: 'the Comoros',
  },
  {
    id: 177,
    label: '코스타리카',
    value: '506',
    code: '+506',
    enLabel: 'Costa Rica',
  },
  {
    id: 178,
    label: '코트디부아르',
    value: '225',
    code: '+225',
    enLabel: 'Ivory Coast',
  },
  { id: 179, label: '콜롬비아', value: '57', code: '+57', enLabel: 'Colombia' },
  {
    id: 180,
    label: '콩고 공화국',
    value: '242',
    code: '+242',
    enLabel: 'Congo',
  },
  {
    id: 181,
    label: '콩고 민주 공화국',
    value: '243',
    code: '+243',
    enLabel: 'DR Congo',
  },
  { id: 182, label: '쿠바', value: '53', code: '+53', enLabel: 'Cuba' },
  { id: 183, label: '쿠웨이트', value: '965', code: '+965', enLabel: 'Kuwait' },
  {
    id: 184,
    label: '쿡 제도',
    value: '682',
    code: '+682',
    enLabel: 'Cook Islands',
  },
  {
    id: 185,
    label: '크로아티아',
    value: '385',
    code: '+385',
    enLabel: 'Croatia',
  },
  {
    id: 186,
    label: '키르기스스탄',
    value: '996',
    code: '+996',
    enLabel: 'Kyrgizstan',
  },
  {
    id: 187,
    label: '키리바시',
    value: '686',
    code: '+686',
    enLabel: 'Kiribati',
  },
  { id: 188, label: '키프로스', value: '357', code: '+357', enLabel: 'Cyprus' },
  {
    id: 189,
    label: '타지키스탄',
    value: '992',
    code: '+992',
    enLabel: 'Tajikistan',
  },
  {
    id: 190,
    label: '탄자니아',
    value: '255',
    code: '+255',
    enLabel: 'Tanzania',
  },
  { id: 191, label: '태국', value: '66', code: '+66', enLabel: 'Thailand' },
  { id: 192, label: '터키', value: '90', code: '+90', enLabel: 'Turkey' },
  { id: 193, label: '토고', value: '228', code: '+228', enLabel: 'Togo' },
  {
    id: 194,
    label: '토켈라우',
    value: '690',
    code: '+690',
    enLabel: 'Tokelau',
  },
  { id: 195, label: '통가', value: '676', code: '+233', enLabel: 'Tonga' },
  {
    id: 196,
    label: '투르크메니스탄',
    value: '993',
    code: '+993',
    enLabel: 'Turkmenistan',
  },
  { id: 197, label: '투발루', value: '688', code: '+688', enLabel: 'Tuvalu' },
  { id: 198, label: '튀니지', value: '216', code: '+216', enLabel: 'Tunisia' },
  {
    id: 199,
    label: '트리니다드 토바고',
    value: '1868',
    code: '+1868',
    enLabel: 'Trinidad and Tobago',
  },
  { id: 200, label: '파나마', value: '507', code: '+507', enLabel: 'Panama' },
  {
    id: 201,
    label: '파라과이',
    value: '595',
    code: '+595',
    enLabel: 'Paraguay',
  },
  { id: 202, label: '파키스탄', value: '92', code: '+92', enLabel: 'Pakistan' },
  {
    id: 203,
    label: '파푸아뉴기니',
    value: '675',
    code: '+675',
    enLabel: 'Papua New Guinea',
  },
  {
    id: 204,
    label: '팔라우',
    value: '680',
    code: '+680',
    enLabel: 'Palau',
  },
  {
    id: 205,
    label: '팔레스타인',
    value: '970',
    code: '+970',
    enLabel: 'State of Palestine',
  },
  { id: 206, label: '페루', value: '51', code: '+51', enLabel: 'Peru' },
  {
    id: 207,
    label: '포르투갈',
    value: '351',
    code: '+351',
    enLabel: 'Portugal',
  },
  {
    id: 208,
    label: '포클랜드 제도',
    value: '500',
    code: '+500',
    enLabel: 'Falkland Islands',
  },
  { id: 209, label: '폴란드', value: '48', code: '+48', enLabel: 'Poland' },
  {
    id: 210,
    label: '푸에르토리코',
    value: '1787',
    code: '+1787',
    enLabel: 'Puerto Rico',
  },
  { id: 211, label: '프랑스', value: '33', code: '+33', enLabel: 'France' },
  { id: 212, label: '피지', value: '679', code: '+679', enLabel: 'Fiji' },
  { id: 213, label: '핀란드', value: '358', code: '+358', enLabel: 'Finland' },
  {
    id: 214,
    label: '필리핀',
    value: '63',
    code: '+63',
    enLabel: 'the Philippines',
  },
  { id: 215, label: '헝가리', value: '36', code: '+36', enLabel: 'Hungary' },
  { id: 216, label: '홍콩', value: '852', code: '+852', enLabel: 'HongKong' },
];
